name: MacOS-Qt6.5.1
on: 
  push:
    paths:
      - '*.txt'
      - '*.bat'
      - '*.sh'
      - '3rdparty/**'
      - 'code/**'
      - 'config/**'
      - 'FluControls/**'
      - 'FluExamples/**'
      - 'FluIconTool/**'
      - 'FluUtils/**'
      - 'FluWinGallery/**'
      - 'res/**'
      - 'StyleSheet/**'
      - '.github/workflows/MacOS-Qt6.5.1.yml'
  pull_request:
    paths:
      - '*.txt'
      - '*.bat'
      - '*.sh'
      - '3rdparty/**'
      - 'code/**'
      - 'config/**'
      - 'FluControls/**'
      - 'FluExamples/**'
      - 'FluIconTool/**'
      - 'FluUtils/**'
      - 'res/**'
      - 'StyleSheet/**'
      - '.github/workflows/MacOS-Qt6.5.1.yml'
      
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        qt_ver: [6.5.1]
        qt_arch: [clang_64]
    env:
      targetName: FluWinGallery
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          cache: ${{steps.cache-qt.outputs.cache-hit}}
          arch: ${{ matrix.qt_arch }}
          modules: 'qt5compat qtmultimedia qtshadertools qtimageformats qt3d'
          
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3
        with:
          version: 1.10.2
          
      - name: Build & Package
        run: |
          cmake --version
          mkdir build
          cd build
          cmake -DCMAKE_MESSAGE_LOG_LEVEL=STATUS -DCMAKE_PREFIX_PATH=/Users/runner/work/CppQtFluentUi888/Qt/${{ matrix.qt_ver }}/macos -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -GNinja ..
          cmake --build . --target all --config Release --parallel
          cmake --build . --target package
          
          
      - name: New Release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/FluGalleryWin64Msvc.zip
          asset_name: ${{ env.targetName }}_${{  github.ref_name }}_${{ matrix.os }}_Qt${{ matrix.qt_ver }}.zip
          tag: ${{ github.ref }}
          overwrite: true
